pbapp/pbapp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static


from store import views

urlpatterns = [
    url('admin/', admin.site.urls),
    url('store/', include('store.urls', namespace='store')),
    url('', views.index)

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pbapp/store/urls.py
from django.conf.urls import url

from . import views


app_name = 'store'
urlpatterns = [
    url(r'^login/$', views.login_, name='login'),
    url(r'^search/$', views.search, name='search'),
    url(r'^show_products/$', views.display_my_products, name='show'),
    url(r'^add_product/(?P<product_id>[0-9]+)/$', views.add_product_to_favorite, name='add'),
    url(r'^index/$', views.index, name='index'),
    url(r'^detail/(?P<id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^log_out/$', views.log_out, name='logOut'),
    url(r'connection/$', views.connect_user, name='connect'),
    url(r'^my_count/$', views.my_count, name='my_count'),
    url(r'^user_register', views.register_, name='register'),
    url(r'^terms_of_use/$', views.terms, name='terms'),
    url(r'change_pass/$', views.change_password, name='changePasswd')
]

pbapp/store/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Favorite(models.Model):
    name = models.CharField(max_length=200)
    generic_name = models.CharField(max_length=300)
    categorie = models.CharField(max_length=200)
    nutriscore = models.CharField(max_length=1)
    picture = models.CharField(max_length=600, null=True)
    id_user = models.ForeignKey(User, on_delete=models.CASCADE, default=00)


class ProductsNutriTypeA(models.Model):
    code = models.CharField(max_length=500, default="00")
    product_name = models.CharField(max_length=300, default="00")
    picture = models.CharField(max_length=500, default="00")
    category = models.CharField(max_length=200, default="00")


class PictureUser(models.Model):
    name = models.CharField(max_length=600, null=True)
    id_user = models.ForeignKey(User, on_delete=models.CASCADE)

pbapp/store/forms.py
from django import forms
from django.forms.utils import ErrorList


class Register(forms.Form):
    name = forms.CharField(
        label="",
        max_length=50,
        widget=forms.TextInput(attrs={'class': 'form-group', 'placeholder': 'Nom'}),
        required=True,

    )
    email = forms.EmailField(
        label="",
        widget=forms.EmailInput(attrs={'class': 'form-group', 'placeholder': 'Email'}),
        required=True
    )
    passwd = forms.CharField(
        label="",
        widget=forms.PasswordInput(attrs={'class': 'form-group', 'placeholder': 'Mot de passe'}),
        required=True
    )


class SearchProduct(forms.Form):
    search = forms.CharField(
        label="",
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'form-inline'}),
        required=False
    )


class LogIn(forms.Form):
    name = forms.CharField(
        label="",
        widget=forms.TextInput(attrs={'class': 'form-group', 'placeholder': 'nom'}),
        required=True
    )
    passwd = forms.CharField(
        label="",
        widget=forms.PasswordInput(attrs={'class': 'form-group', 'placeholder': 'Mot de passe'}),
        required=True
    )


class ParagraphErrorList(ErrorList):
    def __str__(self):
        return self.as_divs()

    def as_divs(self):
        if not self:
            return ''
        return '<div class="errorlist">%s</div>' % ''.join(['<p class="small error">%s</p>' % e for e in self])


class ChangePassword(forms.Form):
    passwd = forms.CharField(
        label="",
        widget=forms.PasswordInput(attrs={'class': 'form-group', 'placeholder': 'Mot de passe'}),
        required=True
    )
    confPasswd = forms.CharField(
        label="",
        widget=forms.PasswordInput(attrs={'class': 'form-group', 'placeholder': 'Confirmer mot de passe'}),
        required=True
    )

pbapp/store/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404, render_to_response
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth import authenticate, login, logout
import random
import logging

from .forms import Register, ParagraphErrorList, SearchProduct, LogIn, ChangePassword
from .request_.offs_req import AllRequests
from .models import ProductsNutriTypeA, Favorite, PictureUser


logger = logging.getLogger(__name__)

# Create your views here.


def index(request):
    """Display index page"""
    user = request.user.id
    if user:
        form = SearchProduct()
        context = {
            'form': form,
            'user': True
        }
        return render(request, 'store/index.html', context)
    else:
        form = SearchProduct()
        context = {'form': form, 'user': False}
        return render(request, 'store/index.html', context)


def register_(request):
    """display register page"""
    form = SearchProduct()
    if request.method == 'POST':
        formr = Register(request.POST, error_class=ParagraphErrorList)
        if formr.is_valid():
            name = formr.cleaned_data['name']
            emailUser = formr.cleaned_data['email']
            passwd = formr.cleaned_data['passwd']
            user = User.objects.create_user(username=name, email=emailUser, password=passwd)
            user.save()
            formlg = LogIn()
            context = {
                'form': form}
            return render(request, 'store/thanks.html', context)
        else:
            forml = Register()
            context = {
                'logEr': True,
                'forml': forml,
                'form': form,
            }
            return render(request, 'store/register_user.html', context)
    else:
        forml = Register()
        context = {
            'forml': forml,
            'form': form,
        }
        return render(request, 'store/register_user.html', context)


def login_(request):
    """log form"""
    form = SearchProduct()
    formlg = LogIn()
    context = {'formlg': formlg,
               'form': form}
    return render(request, 'store/login.html', context)


def my_count(request):
    """account page"""
    form = SearchProduct()
    passForm = ChangePassword()
    user = request.user.id
    try:
        picture = PictureUser.objects.get(id_user=user)
        picture = picture.name
    except Exception:
        picture = ";-)"

    detUser = get_object_or_404(User, pk=user)
    name = detUser.username
    mail = detUser.email
    context = {'name': name,
               'mail': mail,
               'form': form,
               'picture': picture,
               'passwd': passForm,
               }
    return render(request, 'store/my_place.html', context)


def change_password(request):
    """Script for confirm and change password user"""
    if request.method == 'POST':
        formp = ChangePassword(request.POST, error_class=ParagraphErrorList)
        if formp.is_valid():
            userId = request.user.id
            detUser = get_object_or_404(User, pk=userId)
            passwd = formp.cleaned_data['passwd']
            confPasswd = formp.cleaned_data['confPasswd']
            if passwd != confPasswd:
                form = SearchProduct()
                passForm = ChangePassword()
                try:
                    picture = PictureUser.objects.get(id_user=userId)
                    picture = picture.name
                except Exception:
                    picture = ";-)"
                context = {
                    'name': detUser.username,
                    'mail': detUser.email,
                    'form': form,
                    'picture': picture,
                    'passwd': passForm,
                    'logEr': True
                }
                return render(request, 'store/my_place.html', context)
            else:
                detUser.set_password(passwd)
                detUser.save()
                form = SearchProduct()
                passForm = ChangePassword()
                try:
                    picture = PictureUser.objects.get(id_user=userId)
                    picture = picture.name
                except Exception:
                    picture = ";-)"
                context = {
                    'name': detUser.username,
                    'mail': detUser.email,
                    'form': form,
                    'picture': picture,
                    'passwd': passForm,
                    'done': True
                }
                return render(request, 'store/my_place.html', context)


def connect_user(request):
    """Connect the users"""
    if request.method == 'POST':
        form = LogIn(request.POST, error_class=ParagraphErrorList)
        if form.is_valid():
            name = form.cleaned_data['name']
            passwd = form.cleaned_data['passwd']
            user = authenticate(username=name, password=passwd)
            if user is None:
                forml = Register()
                formlg = LogIn()
                form = SearchProduct()
                context = {
                    'user': False,
                    'logEr': True,
                    'forml': forml,
                    'formlg': formlg,
                    'form': form
                }
                return render(request, 'store/login.html', context)
            else:
                login(request, user)
                form = SearchProduct()
                context = {
                    "welcome": True,
                    "form": form
                }
                return render(request, 'store/index.html', context)


def search(request):
    """Display the results for the request"""
    user = request.user.id
    if user:
        user = True
    else:
        user = False
    form = SearchProduct(request.POST, error_class=ParagraphErrorList)
    if form.is_valid():
        item = request.GET['search']
        req = AllRequests()
        prd = req.search_product_item(item)
        print(item)
        product = prd.json()
        if not product['products']:
            context = {
                'user': user,
                'form': form,
                'badSearch': True
            }
            return render(request, 'store/result.html', context)
        product = product['products'][0]
        category_ = product['pnns_groups_2']
        picture = product['image_front_url']
        name = product['product_name']
        aProducts = ProductsNutriTypeA.objects.filter(category=category_)
        aProductl = []
        for prd in aProducts:
            aProductl.append(prd)
        paginator = Paginator(aProductl, 9)
        page = request.GET.get('page')
        try:
            pProducts = paginator.get_page(page)
        except PageNotAnInteger:
            pProducts = paginator.get_page(1)
        except EmptyPage:
            pProducts = paginator.get_page(paginator.num_pages)
        formi = SearchProduct()
        context = {'product': pProducts,
                   'picture': picture,
                   'name': name,
                   'form': formi,
                   'user': user,
                   'item': item
                   }
        logger.info('New search', exc_info=True, extra={
        # Optionally pass a request and we'll grab any information we can
        'request': request, })
        return render(request, 'store/result.html', context)


@login_required
def display_my_products(request):
    """display the favorite"""
    form = SearchProduct
    id_user = request.user.id
    user = get_object_or_404(User, pk=id_user)
    products = get_list_or_404(Favorite, id_user=user)
    favorite = []
    for prd in products:
        bdPrd = get_object_or_404(ProductsNutriTypeA, picture=prd.picture)
        favorite.append(bdPrd)
    paginator = Paginator(favorite, 9)
    page = request.GET.get('page')
    try:
        pProducts = paginator.get_page(page)
    except PageNotAnInteger:
        pProducts = paginator.get_page(1)
    except EmptyPage:
        pProducts = paginator.get_page(paginator.num_pages)
    context = {'products': pProducts,
               'form': form,
               'user': True
               }
    return render(request, 'store/show_products.html', context)


@login_required
def add_product_to_favorite(request, product_id):
    """Add product to favorite"""
    product = get_object_or_404(ProductsNutriTypeA, pk=product_id)
    id_user = request.user.id
    user = get_object_or_404(User, pk=id_user)
    name = product.product_name
    category = product.category
    picture = product.picture
    with transaction.atomic():
        prd = Favorite(name=name, generic_name=name, categorie=category, nutriscore='a', picture=picture,
                       id_user=user)
        prd.save()
    form = SearchProduct()
    context = {'form': form,
               'user': True,
               'name': name,
               'productAdd': True
               }
    return render(request, 'store/index.html', context)


def detail(request, id):
    """Display the product detail"""
    user = request.user.id
    if user:
        user = True
    else:
        user = False
    form = SearchProduct
    product = get_object_or_404(ProductsNutriTypeA, pk=id)
    code = product.code
    req = AllRequests()
    prod = req.code_request(code)
    product = prod.json()
    filtProduct = product['product']
    try:
        pictureFicheNutri = filtProduct['selected_images']['nutrition']['display']['fr']
    except KeyError:
        pictureFicheNutri = None
    filtProduct = product['product']
    try:
        picturePrd = filtProduct['image_front_url']
    except KeyError:
        picturePrd = None

pbapp/store/templates/store/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Pur Beurre</title>
  {% load static %}

  <!-- Font Awesome Icons -->
  <link href='{% static "store/vendor/fontawesome-free/css/all.min.css" %}' rel="stylesheet" type="text/css">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic' rel='stylesheet' type='text/css'>

  <!-- Plugin CSS -->
  <link href='{% static "store/vendor/magnific-popup/magnific-popup.css" %}' rel="stylesheet">

  <!-- Theme CSS - Includes Bootstrap -->
  <link href="{% static 'store/css/creative.min.css' %}" rel="stylesheet">

</head>

<body id="page-top">

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container">
      <img src="{% static 'store/img/biscuit1.png' %}" alt="iône biscuit" ><a class="navbar-brand js-scroll-trigger" href="{% url 'store:index' %}">&nbsp;Pur beurre</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto my-2 my-lg-0">
          <li class="nav-item">
            <form class="form-inline" action="{% url 'store:search' %}" method="get">

           <!-- <input id="inputForm"  type="text" name="texte" style="color : black;"> -->
                {{ form }}

          <button id="envoi" class="nav-link js-scroll-trigger" style="padding-top: 5px;padding-bottom: 5px;"><span style="color:black;">Chercher</span> </button>
            </form>
          </li>
          <li class="nav-item">
            {% if user == True %}
            <a class="nav-link js-scroll-trigger" href="{% url 'store:my_count' %}" ><i class="fas fa-user fa-2x"></i></a>
            {% elif user == False %}
            <a class="nav-link js-scroll-trigger" href="{% url 'store:login' %}" ><i class="fas fa-user fa-2x"></i>&nbsp;Se connecter</a>
            {% elif welcome == True %}
            <a class="nav-link js-scroll-trigger" href="{% url 'store:my_count' %}" ><i class="fas fa-user fa-2x"></i>&nbsp;Bienvenue</a>
            {% endif %}

          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'store:show' %}"><i class="fas fa-carrot fa-2x"></i></a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'store:logOut' %}"><i class="fas fa-sign-out-alt fa-2x"></i></a>
          </li>

        </ul>
      </div>
    </div>
  </nav>

  <!-- Masthead -->

    <div class="container">
      <div class="row justify-content-center">

{% block content %}{% endblock %}
      </div>
    </div>


  <!-- About Section -->


  <!-- Footer -->
  <footer class="fixed-bottom bg-primary">
    <div class="container">
      <div class="row">
  <div class="col-md-6 text-center"><a href="{% url 'store:terms' %}"> Mention légales</a></div>
        <div class="col-md-6 text-center"><a href="store/index/#contact">Contact</a></div>
</div>

    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'store/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'store/vendor/bootstrap/js/bootstrap.min.js' %}"></script>

  <!-- Plugin JavaScript -->
  <script src="{% static 'store/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'store/vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'store/js/creative.min.js' %}"></script>

</body>

</html>

pbapp/store/templates/store/detail.html
{% extends 'store/base.html' %}

{% block content %}
{% load static %}
 <section class="page-section" >
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8 text-center">
            <img src="{{ picture }}" alt="productPicture">
          <h2 class="text-white mt-0">{{ name }}</h2>
          <hr class="divider light my-4">
          <p class="text-white-50 mb-4">Remy et Colette sont amoureux de la gastronomie française (on ne peut les blâmer !). Travaillant quotidiennement avec les meilleurs produits du terroir, ils affectionnent particulièrement la bonne chaire et aiment partager leur passion.</p>
        </div>
      </div>
    </div>
  </section>

<section class="page-section">
    <div class="container justify-content-center">
    <div class="row text-center" >
<img src="{{ nutri_score }}" align="right" alt="nutri_score" style="padding-left: 74px;">
        </div>
    </div>

<p><br></p>
    <div class="container">
    <div class="row text-right ">
    <img src="{{ nutri_pic }}" align="right" alt="imgNutri" >
    </div>
    </div>

    <p><br></p>
    <div class="container">
    <div class="box text-center">
    <a class="btn btn-light btn-xl js-scroll-trigger"  href="https://fr.openfoodfacts.org/produit/{{ code }}">Page officielle du produit</a>
    </div>
    </div>
</section>
{% endblock %}

pbapp/store/templates/store/index.html
{% extends 'store/base.html' %}
{% block content %}
{% load static %}
{% if productAdd == True %}
                   <p><br><br></p>
                    <div class="container">
                        <h2 class="mt-0" style="color:green;">Le produit {{name}} a bien été rajouté a vos favorits.</h2>
                    </div>
{% endif %}
  <section class="page-section justify-content-center" id="about">
    <div class="container">
       <div class="row justify-content-center" >
        <div class="col-lg-8 text-center">
          <h1 class="text-white mt-0 text-center">Du gras oui mais de qualité</h1>
          <h2 class="text-white mt-0">Trouvez un produit de substitution <br>pour ceux que vous consommez tous les jours</h2>
          <hr class="divider light my-4">
            <form class="form-inline" action="{% url 'store:search' %}" method="get">

         {{ form }}
          <button type="submit" class="btn btn-success" >Chercher</button>
                {% if badSearch == True %}
                    <h2 class="mt-0" style="color:red;">Le produit que vous recherchez n'existe pas.</h2>
                {% endif %}

            </form>
        </div>
      </div>>

        </div>
  </section>
 <section class="page-section" id="contact">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8 text-center">
          <h2 class="text-white mt-0">Colette et Remy</h2>
          <hr class="divider light my-4">
          <p class="text-white-50 mb-4">Remy et Colette sont amoureux de la gastronomie française (on ne peut les blâmer !). Travaillant quotidiennement avec les meilleurs produits du terroir, ils affectionnent particulièrement la bonne chaire et aiment partager leur passion.</p>
        </div>

        <div class="col-md-6">
          <img src="{% static 'store/img/colette-tatou1.png' %}" alt="imgCo">
          <img src="{% static 'store/img/ratatouille2.png' %}" alt="imgRe">
        </div>
      </div>
    </div>
  </section>
  <section class="page-section justify-content-center" id="services" >
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8 text-center">
<h2 class="text-white mt-0 text-center">Contactez-nous</h2>
<hr class="divider my-4">
          <p class="mb-4 text-center" style="color:green;">La maison est grande ouverte.</p>
        </div>
      </div>


      <div class="row">
        <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
          <i class="fas fa-phone fa-3x mb-3 text-muted"></i>
          <div class="text-white-50 mb-4"><p style="color:orange;">+1 (202) 555-0149</p></div>
        </div>
        <div class="col-lg-4 mr-auto text-center">
          <i class="fas fa-envelope fa-3x mb-3 text-muted"></i>
          <!-- Make sure to change the email address in anchor text AND the link below! -->
          <div class="text-white-50 mb-4"><a href="mailto:contact@yourwebsite.com"><p style="color:orange;">contact@yourwebsite.com</p></a> </div>
        </div>
      </div>>


      </div>
    </div>
  </section>
{% endblock %}

pbapp/store/templates/store/login.html
{% extends 'store/base.html' %}

{% block content %}
<section class="justify-content-center">
<div class="box"></div>
</section>
 <form action="{% url 'store:connect' %}" method="post">
     <p><h1><br><br><br></h1></p>
      {% csrf_token %}
    {{ formlg }}
      <button type="submit" class="btn btn-success"><i class="fas fa-save">Connecter</i></button>
      <h3 class="text-white mt-0 text-center">  <a href="{% url 'store:register' %}"><em>Inscription</em></a> </h3>
      {% if logEr == True %}<h3 class="text-white mt-0 text-center">Veuillez vérifier vos informations, ou vous enregistrer via le lien ci-dessus. Merci.</h3>{% endif %}
  </form>






{% endblock %}

pbapp/store/templates/store/my_count.html
{% extends 'store/base.html' %}
{% block content %}
<section class="page-section">

    <div class="container">
       <div class="row justify-content-center" style="margin-left: 476px;">
        <div class="col-lg-8 text-center">
          <h1 class="text-white mt-0 text-center">{{ name }}</h1>
          <hr class="divider light my-4" style="margin-left: 4px;border-left-width: 5.2rem;border-left-style: solid;">

        </div>
      </div>>

        </div>
      </div>
    </div>
  </section>
<img  src="{{ picture }}" alt="{{ name }}" width="250" height="300">
<section class="page-section">

    <div class="container">
       <div class="row justify-content-center">
        <div class="col-lg-8 text-center">
          <h1 class="text-white mt-0 text-center">{{ mail }}</h1>
          <hr class="divider light my-4">
        </div>
      </div>>

        </div>
      </div>
    </div>

  </section>
{% endblock %}

pbapp/store/templates/store/my_place.html
{% extends 'store/base.html' %}
{% block content %}
{% load static %}
<section class="page-section">

    <div class="container">
       <div class="row justify-content-center">
        <div class="col-lg-8 text-center">
            <img  src="{% static 'store/img/user/' %}{{ picture }}" alt="{{ name }}">
          <h1 class="text-white mt-0 text-center">{{ name }}</h1>
          <hr class="divider light my-4">

        </div>
      </div>>

        </div>
      </div>
    </div>
  </section>

<section class="page-section">

    <div class="container">
       <div class="row justify-content-center">
        <div class="col-lg-8 text-center">
          <h1 class="text-white mt-0">{{ mail }}</h1>
          <hr class="divider light my-4">
            <p class="text-white mt-0">Vous pouvez changer votre mot de passe ici </p>
            <form class="form-inline" action="{% url 'store:changePasswd' %}" method="post">
                {% csrf_token %}
            {{ passwd }}
                <button type="submit" class="btn btn-success"><i class="fas fa-save">Changer</i></button>
            </form>
            {% if done == True %}<p class="text-white mt-0">Vous avez changé votre mot de passe</p>
            {% elif logEr == True %}<h3 class="text-white mt-0 text-center">Veuillez vérifier vos informations</h3>
            {% endif %}
        </div>
      </div>>

        </div>


  </section>
{% endblock %}

pbapp/store/templates/store/register_user.html
{% extends 'store/base.html' %}
{% block content %}


    <form action="{% url 'store:register' %}" method="post">
      <p><h1><br><br><br></h1></p>

    {% csrf_token %}
      {{ forml }}
    <button type="submit" class="btn btn-success">Enregistrer</button>
        {% if logEr == True %}<h3 class="text-white mt-0 text-center">Veuillez vérifier vos informations. Merci.</h3>{% endif %}
</form>


{% endblock %}

pbapp/store/templates/store/result.html
{% extends 'store/base.html' %}

{% block content %}
<section  class="page-section" >
    <div class="container">

      <div class="row justify-content-center">

        <div class="col-lg-8 text-center">
            <img src="{{ picture }}" alt="productPicture">
          <h2 class="text-white mt-0">{{ name }}</h2>
          <hr class="divider light my-4">
          <p class="text-white-50 mb-4">Les produits proposés par les grandes marques sont-ils de qualité supérieure par rapport aux produits sans marque ? La question mérite d’être posée. Ici pas de distinction de marque mais de qualité</p>
        </div>
      </div>
    </div>
  </section>
<div class="container">
<div class="col-lg-8 text-center">
<p class="text-white-50 mb-4 text-center">Vous pouvez remplacer ce produit par:</p>
</div>
</div>
{% for prd in product %}

        <div class="col-md-4 result" >

            <a href="{% url 'store:detail' id=prd.id %}"><em>Voir produit</em> </a><div class="text-right"><i class="fas fa-font" style="color:green;"></i></div><p><br></p>

              <img class="img-responsive" src="{{ prd.picture }}" alt="{{ prd.product_name }}" width="auto" height="300">

            <h3><a href="{% url 'store:add' product_id=prd.id %}"><i class="fas fa-save"></i>{{ prd.product_name }}</a></h3>
        </div>
        {% if forloop.counter|divisibleby:3 %}<div class="clearfix"></div>{% endif %}


{% endfor %}
<div class="pagination">
  <div class="clearfix"></div>
  <nav aria-label="">
    <ul class="pager">
        <div class="row">
      {% if product.has_previous %}
        <div class="col-md-6 text-center"><li class="col-md-6"><a href="?search={{ item }}&page={{ product.previous_page_number }}">Précédent</a></li></div>
      {% endif %}
      {% if product.has_next %}
        <div class="col-md-6 text-center"><li><a href="?search={{ item }}&page={{ product.next_page_number }}">Suivant</a></li></div>
      {% endif %}</div>
    </ul>
  </nav>
</div>
<section><p> <br><br></p></section>





{% endblock %}

pbapp/store/templates/store/show_products.html
{% extends 'store/base.html' %}
{% block content %}
<section  class="page-section" >
    <div class="container">
      <div class="row justify-content-center">

        <div class="col-lg-8 text-center">
            <img src="{{ picture }}" alt="productPicture">
          <h2 class="text-white mt-0">Mes produits favoris</h2>
          <hr class="divider light my-4">
          <p class="text-white-50 mb-4">Ici vous pouvez retrouver vos produits de meilleurs qualité, n'hésitez pas à faire de nouvelle expériences culinaire car le meilleur reste à venir.</p>
        </div>
      </div>
    </div>
  </section>

    {% for prd in products %}

            <div class="col-md-4 result">
            <a href="{% url 'store:detail' id=prd.id %}">
              <img class="img-responsive" src="{{ prd.picture }}" alt="{{ prd.name }}" width="auto" height="300">
            </a>
            <h3><a>{{ prd.name }}</a></h3>
        </div>
        {% if forloop.counter|divisibleby:3 %}<div class="clearfix"></div>{% endif %}


{% endfor %}
<div class="pagination">
  <div class="clearfix"></div>
  <nav aria-label="">
    <ul class="pager">
        <div class="row">
      {% if products.has_previous %}
        <div class="col-md-6 text-center"><li class="col-md-6"><a href="?page={{ products.previous_page_number }}">Précédent</a></li></div>
      {% endif %}
      {% if products.has_next %}
        <div class="col-md-6 text-center"><li><a href="?page={{ products.next_page_number }}">Suivant</a></li></div>
      {% endif %}</div>
    </ul>
  </nav>
</div>
<section><p> <br><br></p></section>

{% endblock %}

pbapp/store/templates/store/thanks.html
{% extends 'store/base.html' %}
{% block content %}
<div class="container justify-content-center">
       <div class="row justify-content-center" style="margin-left: 144px;">
        <div class="col-lg-8 text-center" style="top: 300px;">
          <h1 class="text-white mt-0">Merci, de passer nous voir.</h1>
          <h2 class="text-white mt-0">Vous êtes le bienvenue.</h2>
          <hr class="divider light my-4">

        </div>
       </div>>

    </div>

{% endblock %}